const quizData = [
  { question: "Você está perdendo dinheiro com apostas? 💸",
    answers: ["Sim, várias vezes", "Algumas vezes", "Poucas vezes", "Não, mas sempre fico preocupado"],
    feedback: "Sozinho é fácil perder. Mas existe uma forma de mudar isso." },
  { question: "Você se sente confiante ao identificar oportunidades reais de lucro sozinho? 🤔",
    answers: ["Nunca", "Quase nunca", "Às vezes", "Sim, mas com dúvidas"],
    feedback: "Mesmo apostadores experientes erram sozinho. A IA te dá vantagem." },
  { question: "Com que frequência você confia apenas na sorte ao apostar? 🎲",
    answers: ["Sempre", "Frequentemente", "Às vezes", "Quase nunca"],
    feedback: "Confiar na sorte sozinho é arriscado. Informação = ganho." },
  { question: "Você já perdeu oportunidades de lucro por não ter alertas rápidos? ⏱️",
    answers: ["Sim, várias vezes", "Algumas vezes", "Poucas vezes", "Nunca"],
    feedback: "A IA garante que você seja informado no momento certo." },
  { question: "Ter alertas prontos e uma comunidade ativa ajudaria você a ganhar mais? 📈",
    answers: ["Sim, imediatamente", "Claro", "Com certeza", "Talvez, mas vale tentar"],
    feedback: "Exatamente, é assim que nosso grupo maximiza oportunidades." },
  { question: "Você quer parar de perder e começar a aproveitar cada oportunidade de lucro? 💰",
    answers: ["Sim, quero agora", "Sim, definitivamente", "Claro", "Com certeza"],
    feedback: "Ótimo! O próximo passo é garantir sua vaga no
